### ISSUE TITLE
When I execute "main_eval_plm_wsp. sh", the results are all 0.

### ISSUE THREAD

**Issue by luojintao** [Bahuia/HGNet#2]
<img width="887" alt="1667376722752" src="https://user-images.githubusercontent.com/57553975/199434936-b960f21c-22bf-483d-9793-f7b0dcac68bd.png">

![image](https://user-images.githubusercontent.com/57553975/199435360-ed1afe61-bf48-48ff-b7b5-2a099a4721aa.png)

When I execute "main_eval_wsp. sh", it works fine.
![image](https://user-images.githubusercontent.com/57553975/199437147-2bf9da97-d3f2-44b8-a3b2-d595b8c4ba28.png)

The same problem occurs when I execute "main_eval_plm_cwq. sh".

**Comment by Bahuia** [comment]
We have recently updated the code, vocabulary and trained models. Please try again. But be sure to download and use the virtuoso service we provide and modify the kb_endpoint in the eval_plm_cwq.sh file, as it involves our model's query to KG when executing the EG strategy.

**Comment by shall-learn** [comment]
I use the latest version and modify the kb_endpoint in the eval_plm_cwq.sh file and eval_cwq.sh file, but the results are still empty. If i add "--not_use_eg", they work fine
